# Generated by Django 5.2.9 on 2025-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
